/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pfvrfurkncmwnyzgldhc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdnJmdXJrbmNtd255emdsZGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1NTU1NzIsImV4cCI6MjEwMTEzMTU3Mn0.8oM3IlK-wpNJtl-GC9Q9BQq7PXFLOo43A9-HaGi_w4w"